### ISSUE TITLE
Use source_users for autoprovisioning

### ISSUE THREAD

**Issue by buchi** [4teamwork/ftw.saml2auth#6]
Create users in the default source_users plugin instead of implementing our own one.

**Comment by elioschmutz** [comment]
If we use the source_users for autoprovisioning, we would remove the control to manage users through the AD.

I.e. with the current implementation, an internal user in the AD can be deactivated through the AD. The user could no longer login.

If we would use the source_users, the user could change his plone-password and if he gets deactivated in the AD, he can still login from an external network with its plone-user and password.

This is the reason why we don't implement this enhancement.
